name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: |
          set -e
          rustup set profile minimal
          rustup install stable
          cargo install --force cargo-make
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      # - name: vuln
      #   run: cargo make vuln
      - name: lint
        run: cargo make lint
      - name: test
        run: cargo make test
      - name: build
        run: cargo make build
